// <auto-generated />
using System;
using Horizon2000Rest.Entity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Horizon2000Rest.Entity.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230511093115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.AdvertDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Advert");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.BookingDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<short?>("PaymentType")
                        .HasColumnType("smallint");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("SkillCardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ClientDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.CourseDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("NormalHour")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("NormalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ParentCourseId")
                        .HasColumnType("int");

                    b.Property<byte>("RapidHour")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("RapidPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ParentCourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ParentCourseDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SkillCardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestConditions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ParentCourse");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(3782),
                            ImagePath = "C:\\Images\\ECDL_logo.png",
                            IsActive = false,
                            Name = "ECDL Base & Standard"
                        },
                        new
                        {
                            ID = 4,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(3802),
                            ImagePath = "C:\\Images\\ECDL_Logo.png",
                            IsActive = true,
                            Name = "ECDL Advanced"
                        },
                        new
                        {
                            ID = 5,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(3815),
                            ImagePath = "C:\\Images\\Matsec.png",
                            IsActive = true,
                            Name = "Matsec"
                        },
                        new
                        {
                            ID = 6,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(3868),
                            ImagePath = "C:\\\\Images\\icdl_logo.png",
                            IsActive = false,
                            Name = "ICDL"
                        });
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ProductCategoryDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3884),
                            IsActive = true,
                            Name = "Mice"
                        },
                        new
                        {
                            ID = 2,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3897),
                            IsActive = true,
                            Name = "Joysticks"
                        },
                        new
                        {
                            ID = 3,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3907),
                            IsActive = true,
                            Name = "Cables"
                        },
                        new
                        {
                            ID = 4,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3917),
                            IsActive = true,
                            Name = "Storage Media"
                        },
                        new
                        {
                            ID = 5,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3926),
                            IsActive = true,
                            Name = "Routers"
                        },
                        new
                        {
                            ID = 6,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3937),
                            IsActive = true,
                            Name = "UPS"
                        },
                        new
                        {
                            ID = 7,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3946),
                            IsActive = true,
                            Name = "Hubs"
                        },
                        new
                        {
                            ID = 1002,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3955),
                            IsActive = false,
                            Name = "Mice"
                        },
                        new
                        {
                            ID = 1003,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3964),
                            IsActive = false,
                            Name = "Mice"
                        },
                        new
                        {
                            ID = 1004,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3974),
                            IsActive = false,
                            Name = "Mice"
                        },
                        new
                        {
                            ID = 1005,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3984),
                            IsActive = true,
                            Name = "Laptops"
                        },
                        new
                        {
                            ID = 1006,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(3993),
                            IsActive = true,
                            Name = "Towers (CPU)"
                        },
                        new
                        {
                            ID = 1007,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4002),
                            IsActive = true,
                            Name = "Tablets"
                        });
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ProductDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.RepairDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClientId");

                    b.ToTable("Repair");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.RoleDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ScheduleDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CourseId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ScrollingTextDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScrollText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ScrollingText");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4040),
                            ScrollText = "Website still in progress..."
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4052),
                            ScrollText = "BACK TO SCHOOL:  MATSEC COMPUTING starting 15th October 2020;  ECDL Standard and Advanced ECDL starting on 28th October 2020 "
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4064),
                            ScrollText = "BACK TO SCHOOL:  MATSEC COMPUTING starting 15th October 2020;  ECDL Standard and Advanced ECDL starting on 28th October 2020; A+Computer Technician starting on 3rd November 2020.......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com "
                        },
                        new
                        {
                            ID = 4,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4075),
                            ScrollText = "BACK TO SCHOOL:  MATSEC COMPUTING starting 15th October 2020;  ECDL Standard and Advanced ECDL starting on 28th October 2020; A+Computer Technician starting on 3rd November 2020.......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com "
                        },
                        new
                        {
                            ID = 5,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4084),
                            ScrollText = "BACK TO SCHOOL:  MATSEC COMPUTING starting 15th October 2020;  ECDL Standard and Advanced ECDL starting on 28th October 2020; A+Computer Technician starting on 3rd November 2020.......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com "
                        },
                        new
                        {
                            ID = 6,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4094),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com "
                        },
                        new
                        {
                            ID = 7,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4104),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com "
                        },
                        new
                        {
                            ID = 8,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4114),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com     We wish a Happy New Year 2021 for all our customers, please note that we are operating in full at 94, Triq De Rohan, Haz-Zebbug"
                        },
                        new
                        {
                            ID = 9,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4124),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com     We wish a Happy New Year 2021 for all our customers, please note that we are operating in full at 94, Triq De Rohan, Haz-Zebbug"
                        },
                        new
                        {
                            ID = 1008,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4135),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com     We are fully in operation from  94, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Triq De Rohan, Haz-Zebbug)"
                        },
                        new
                        {
                            ID = 1009,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4145),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 79462236 or email horizon2000computers@gmail.com     We are fully in operation from  94, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Triq De Rohan, Haz-Zebbug) Opening Hours from 4pm - 7pm Mon - Fri and Sat from 9am - 12pm"
                        },
                        new
                        {
                            ID = 1010,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4155),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com     We are fully in operation from  94, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Triq De Rohan, Haz-Zebbug) Opening Hours from 4pm - 7pm Mon - Fri and Sat from 9am - 12pm"
                        },
                        new
                        {
                            ID = 1011,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4222),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com     We are fully in operation from  HORIZON 2000 Computer Training Centre, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Triq De Rohan, Haz-Zebbug) Opening Hours from 4pm - 7pm Mon - Fri and Sat from 9am - 12pm"
                        },
                        new
                        {
                            ID = 1012,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4233),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com      HORIZON 2000 Computer Training Centre, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Triq De Rohan, Haz-Zebbug) Opening Hours from 4pm - 7pm Mon - Fri and Sat from 9am - 12pm"
                        },
                        new
                        {
                            ID = 1013,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4243),
                            ScrollText = "New courses ECDL Standard and ECDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com  -------    HORIZON 2000 Computer Training Centre, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Haz-Zebbug) Opening Hours from 10am - 7pm Mon - Fri and Sat from 9am - 12pm"
                        },
                        new
                        {
                            ID = 1014,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4254),
                            ScrollText = "New courses ICDL Standard and ICDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com  -------    HORIZON 2000 Computer Training Centre, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Haz-Zebbug) Opening Hours from 10am - 7pm Mon - Fri and Sat from 9am - 12pm                      STARTING ON 16/08/2022 ICDL Advanced course Booking open"
                        },
                        new
                        {
                            ID = 1015,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4264),
                            ScrollText = "New courses ICDL Standard and ICDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com  -------    HORIZON 2000 Computer Training Centre, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Haz-Zebbug) Opening Hours from 10am - 7pm Mon - Fri and Sat from 9am - 12pm                      STARTING ON 16/08/2022 ICDL Advanced course Booking open"
                        },
                        new
                        {
                            ID = 2014,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 9, 31, 15, 412, DateTimeKind.Utc).AddTicks(4275),
                            ScrollText = "New courses ICDL Standard and ICDL Advanced......BOOK Now call us on 2146 22 36 or 79462236 or email horizon2000computers@gmail.com  -------    HORIZON 2000 Computer Training Centre, TRIQ DE ROHAN, HAZ-ZEBBUG (near the Boys Museum Haz-Zebbug) Opening Hours from 10am - 7pm Mon - Fri and Sat from 9am - 12pm         BACK TO SCHOOL Winter Schedule lessons NOW AVAILABLE.......BOOK NOW"
                        });
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.StudentCourseSkillCardDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParentCourseID")
                        .HasColumnType("int");

                    b.Property<string>("SkillCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentCourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentCourseSkillCard");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.StudentDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.UserDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Active = false,
                            DateRegistered = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4288),
                            Email = "horizon2000computers@gmail.com",
                            Name = "Martin",
                            Password = "5F7C6C6AEC4B3C1930C473E2FAB6FA2450165F6BBBE4859698682C7670FC8DFDCE560CB51CCD07807F79F3AFB4AE87E5B2C6D2AFB941BE4DB985D1840FC7E05B",
                            Surname = "Sultana",
                            Username = "MSULTANA"
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            DateRegistered = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4300),
                            Email = "horizon2000support@gmail.com",
                            Name = "Antoine",
                            Password = "69C06F6AAC655F931E600F78BB2A6DF3DF6FBF782E074C0880137AC17BA50FBD7E8D50FF15698BD70A76B65BA6BC18EB523D2BA6815F8AF1B18E5E4DF976AA2E",
                            Surname = "Schembri",
                            Username = "antoine"
                        },
                        new
                        {
                            ID = 1002,
                            Active = true,
                            DateRegistered = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4311),
                            Email = "horizon2000computers@gmail.com",
                            Name = "Martin",
                            Password = "E2DCA7EA23086019C94DEDB30BC3A262BD23B3DBE124FB828E144DDEC0C6F6CC7A139156EEB43EC4A0CA50093B9C90C9449C6ECE2AE5DA11898F280484151A97",
                            Surname = "Sultana",
                            Username = "SultanaM"
                        },
                        new
                        {
                            ID = 1003,
                            Active = false,
                            DateRegistered = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4321),
                            Email = "horizon2000sales@gmail.com",
                            Name = "Abigail",
                            Password = "17B510A656C9B8D9A0FBF14172FE35E2CC18428D4DA605AA1F8BD1FC4D6F33828F817E977D832ED78D32D9057B6737113017B0BA03061DE341ED8691F1A14DBE",
                            Surname = "Sultana",
                            Username = "sales"
                        });
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.UserRoleDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Active = false,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4336),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4350),
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            ID = 1002,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4361),
                            RoleId = 1,
                            UserId = 1002
                        },
                        new
                        {
                            ID = 1003,
                            Active = true,
                            DateCreated = new DateTime(2023, 5, 11, 11, 31, 15, 412, DateTimeKind.Local).AddTicks(4373),
                            RoleId = 1,
                            UserId = 1003
                        });
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.UserSessionDbo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.BookingDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.ScheduleDbo", "Schedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horizon2000Rest.Entity.Models.StudentDbo", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.CourseDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.ParentCourseDbo", "ParentCourse")
                        .WithMany("Courses")
                        .HasForeignKey("ParentCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCourse");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ProductDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.ProductCategoryDbo", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.RepairDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.ClientDbo", "Client")
                        .WithMany("Repairs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ScheduleDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.CourseDbo", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.StudentCourseSkillCardDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.ParentCourseDbo", "ParentCourse")
                        .WithMany("StudentCourseSkillCards")
                        .HasForeignKey("ParentCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horizon2000Rest.Entity.Models.StudentDbo", "Student")
                        .WithMany("StudentCourseSkillCard")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCourse");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.UserRoleDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.RoleDbo", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Horizon2000Rest.Entity.Models.UserDbo", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.UserSessionDbo", b =>
                {
                    b.HasOne("Horizon2000Rest.Entity.Models.UserDbo", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ClientDbo", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.CourseDbo", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ParentCourseDbo", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentCourseSkillCards");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ProductCategoryDbo", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.RoleDbo", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.ScheduleDbo", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.StudentDbo", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("StudentCourseSkillCard");
                });

            modelBuilder.Entity("Horizon2000Rest.Entity.Models.UserDbo", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
