// Import necessary libraries for data annotations and table setup
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// This code is enclosed in a namespace, which is a way to group related classes.
namespace Horizon2000Rest.Entity.Models
{
    // The Table attribute allows you to specify the details of the table that this class will map to.
    [Table("Course")]
    // Define a public class, named 'CourseDbo'. This class will represent a 'Course' within the application.
    public class CourseDbo
    {
        // Key attribute denotes that the 'ID' property is a primary key in the database.
        // DatabaseGenerated attribute specifies that the value of 'ID' will be generated by the database when a row is inserted.
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; } // ID property for the course.

        // Required attribute means this field must have data, it can't be left blank.
        [Required]
        public string Name { get; set; } // Name of the course.

        [Required]
        public string Description { get; set; } // Description of the course.

        [Required]
        public byte NormalHour { get; set; } // Normal hours for the course.

        [Required]
        public decimal NormalPrice { get; set; } // Normal price for the course.

        [Required]
        public byte RapidHour { get; set; } // Rapid hours for the course.

        [Required]
        public decimal RapidPrice { get; set; } // Rapid price for the course.

        [Required]
        public bool IsActive { get; set; } // A boolean indicating whether the course is active.

        [Required]
        public DateTime DateCreated { get; set; } = DateTime.Now; // The date the course was created, set to the current date and time by default.

        [Required]
        public int ParentCourseId { get; set; } // ID of the parent course.

        [Required]
        public string ImagePath { get; set; } // Path of the course image.

        // A property to hold the related ParentCourse object. This is known as a navigation property, it allows for easy navigation of related entities in the database.
        public virtual ParentCourseDbo ParentCourse { get; set; }

        // A property to hold a collection of related Schedule objects. Again, this is a navigation property.
        public virtual ICollection<ScheduleDbo> Schedules { get; set; }
    }
}
